-- 082_exercises_preview_svg.sql
-- Stores a pre-rendered SVG of the drill diagram (from Fabric fc.toSVG()) so cards/prints can show the real
-- diagram without loading Fabric. Generated by the Drill Designer on save.
alter table public.exercises add column if not exists preview_svg text;
comment on column public.exercises.preview_svg is 'Pre-rendered SVG of the drill diagram (Fabric toSVG), shown in cards/prints.';
-- No RLS/grants changes: inherits existing exercises policies.
